spring.cloud.config.label=@mw-offer-service-configs-scc-tag@
debug=false
server.port=8080
springdoc.show-actuator=true
#For Spring Boot Actuator
management.endpoints.web.exposure.include=health,info,liveness, readiness,loggers
#Default Profile
#spring.profiles.active=int
#For Config Server
spring.application.name=mw-offer-service-configs
spring.main.allow-bean-definition-overriding=true
#Liveness & Readiness state
management.endpoint.health.probes.enabled=true
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true
#Packages to include
springdoc.packagesToScan=com.xyz.enterprise.offer
profile.upload.attempts=3
ahp.requestTemplate=ahpRequest
ahp.maxTotalConnections=20
ahp.maxConnectionsPerRoute=10
ahp.readTimeout=20000
ahp.connectTimeout=5000
ahp.username=WSxyz00CPF
ahp.organization=HTL-xyz
ahp.offer.profile.version.v1=1000
ahp.offer.profile.version.v2=2000
ahp.offer.profile.version.v3=3000
ahp.offer.profile.version.v4=4000
ahp.offer.profile.version.v5=5000
executor.poolSize=30-60
prodlist=prod,sprod,iadd1,sjcd1
httpConnectionMgr.maxConnections=100
httpConnectionMgr.maxConnectionsTotal=300
httpConnectionMgr.readTimeout=30000
httpConnectionMgr.connectTimeout=10000
hqt.httpConnection.connectTimeout=5000
hqt.httpConnection.readTimeout=30000
smtp.host=smtprelay.hiw.com
smtp.port=25
smtp.connectionTimeout=10000
smtp.IOTimeout=10000
mail.from.hqt.error=offer-profiles
mail.to.hqt.error=vera.ratkevich@xyz.com
mail.hqt.error.subject=Vendor %s information could not be sent to HQT Service
mail.hqt.error.text=Vendor %s information could not be sent to HQT Service.\nPlease verify that the service is up and running.
offer.esb.region.switch=true
restart.include.dozer=/dozer-5.5.1.jar
clientsThatUseOverrides=B2B
amazon.dynamodb.endpoint=http://localhost:8000/
amazon.aws.accesskey=test
amazon.aws.secretkey=test
executor.queueCapacity=1000