debug=false

server.port=8080

springdoc.show-actuator=true

#For Spring Boot Actuator
management.endpoints.web.exposure.include=beans, loggers, metrics, health, info, env, heapdump, refresh

#Default Profile
spring.profiles.active=int

spring.main.allow-bean-definition-overriding=true

#Liveness & Readiness state
management.endpoint.health.probes.enabled=true
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true

#Packages to include
springdoc.packagesToScan=com.xyz.enterprise.offer

ref.data.httpConnection.readTimeout=5000
ref.data.httpConnection.connectTimeout=3000
ref.data.region.countries.path=locations/v1/regionCountries
ref.data.region.countries.url=${ref.data.esb.host}/${ref.data.region.countries.path}/?qRegionTypeCode={qRegionTypeCode}

profile.upload.attempts=3
ahp.requestTemplate=ahpRequest

ahp.maxTotalConnections=20
ahp.maxConnectionsPerRoute=10
ahp.readTimeout=20000
ahp.connectTimeout=5000
ahp.username=WSxyz00CPF
ahp.organization=HTL-xyz

ahp.offer.profile.version.v1=1000
ahp.offer.profile.version.v2=2000
ahp.offer.profile.version.v3=3000
ahp.offer.profile.version.v4=4000
ahp.offer.profile.version.v5=5000

executor.poolSize=30-60

prodlist=prod,sprod,iadd1,sjcd1

hqt.httpConnection.connectTimeout=5000
hqt.httpConnection.readTimeout=30000

smtp.host=smtprelay.hiw.com
smtp.port=25
smtp.connectionTimeout=10000
smtp.IOTimeout=10000

mail.from.hqt.error=offer-profiles
mail.to.hqt.error=vera.ratkevich@xyz.com
mail.hqt.error.subject=Vendor %s information could not be sent to HQT Service
mail.hqt.error.text=Vendor %s information could not be sent to HQT Service.\nPlease verify that the service is up and running.

LOCATION=DC4

default.httpConnection.readTimeout=3000
default.httpConnection.connectTimeout=1000

offer.esb.region.switch=true

restart.include.dozer=/dozer-5.5.1.jar

springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# Hotel Profile API of Property Service, We call over apigee . HCS API direct call is not happening from offer
hotel.details.apigee.url=${hotel.details.apigee.endpoint}/hotels/v1/profiles/
hotel.details.v3.apigee.url=${hotel.details.apigee.endpoint}/hotels/v3/profiles/

caffeine.config.maxsize=10000
caffeine.config.expirationtime=1440

hcs.caffeine.config.maxsize=10000
hcs.caffeine.config.expirationtime=2880

# intentionally increasing timeout to AHP
ahp.read.timeout=30000

offer.dax.endpoint.url=daxs://dax.test.amazonaws.com
isDaxEnabled=false

# EDA Topics
eda.kafka.offer.feeds.topic=synchronize_offer_profiles
eda.kafka.offer.feeds.audit.topic=synchronize_offer_profiles_audit
eda.kafka.offer.feeds.error.topic=synchronize_offer_profiles_error

# EDA Kafka
eda.kafka.primary.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="${eda.kafka.primary.sasl.username}" password="${eda.kafka.primary.sasl.password}";
eda.kafka.dr.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="${eda.kafka.dr.sasl.username}" password="${eda.kafka.dr.sasl.password}";

# Producer FTS
fts.freeVariables.global.service.producer.endpoint.url=${feature.toggle.service.base.uri}/v1/api/freeVariables/global
fts.freeVariables.global.service.delay=30000
eda.kafka.wid=chs