logging.level.root=INFO

#DynamoDB table details configuration
amazon.aws.role.arn=arn:aws:iam::811307098632:role/dynamodb-access-role-offer-chs-cit
amazon.aws.role.sessionname=tryDax
offer.dynamodb.tablename=offer-chs-cit
offer.dynamodb.gsiname=GSI1
offer.dynamodb.secondary.gsiname=GSI2

LOCATION=us_east_1

hotel.details.apigee.endpoint=https://int-api.xyz.com

offer.dynamodb.masterids.initial.value=725000

aws.region=us-east-1
offer.dax.endpoint.url=daxs://chanl-chs-cit-es-dax.cznaja.dax-clusters.us-east-1.amazonaws.com
isDaxEnabled=true

# EDA Primary Configuration
eda.kafka.primary.bootstrap.servers=lkc-nypknz.dom8pmy8vpy.us-east-1.aws.confluent.cloud:9092
eda.kafka.primary.sasl.username={cipher}xxx
eda.kafka.primary.sasl.password={cipher}yyy

# EDA DR Configuration
eda.kafka.dr.bootstrap.servers=lkc-dg5ymy.domxp876rgd.eu-west-2.aws.confluent.cloud:9092
eda.kafka.dr.sasl.username={cipher}xxx
eda.kafka.dr.sasl.password={cipher}yyy

# Producer FTS
feature.toggle.service.base.uri=https://featuretoggle-int.np.ni.microservices.xyz.com