/*
 * Historic Reservation Search
 * Search for reservations. 
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.xyz.enterprise.common.log;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;

public class Permission implements Serializable {
  @JsonProperty("canAccess")
  private Boolean canAccess = false;

  @JsonProperty("canViewPII")
  private Boolean canViewPII = false;

  @JsonProperty("canSendFolio")
  private Boolean canSendFolio = false;

  @JsonProperty("canSendGRU")
  private Boolean canSendGRU = false;

  @JsonProperty("isAdmin")
  private Boolean isAdmin = false;

  public Permission canAccess(Boolean canAccess) {
    this.canAccess = canAccess;
    return this;
  }

  public void setAdmin(Boolean admin) {
    isAdmin = admin;
  }

  /**
   * Get canAccess
   * @return canAccess
  **/
  @Schema(required = true, description = "")
  public Boolean isCanAccess() {
    return canAccess;
  }

  public Permission canViewPII(Boolean canViewPII) {
    this.canViewPII = canViewPII;
    return this;
  }

   /**
   * Get canViewPII
   * @return canViewPII
  **/
  @Schema(required = true, description = "")
  public Boolean isCanViewPII() {
    return canViewPII;
  }

  public Permission canSendFolio(Boolean canSendFolio) {
    this.canSendFolio = canSendFolio;
    return this;
  }

   /**
   * Get canSendFolio
   * @return canSendFolio
  **/
  @Schema(required = true, description = "")
  public Boolean isCanSendFolio() {
    return canSendFolio;
  }

  public Permission canSendGRU(Boolean canSendGRU) {
    this.canSendGRU = canSendGRU;
    return this;
  }

   /**
   * Get canSendGRU
   * @return canSendGRU
  **/
  @Schema(required = true, description = "")
  public Boolean isCanSendGRU() {
    return canSendGRU;
  }

  public Permission isAdmin(Boolean isAdmin) {
    this.isAdmin = isAdmin;
    return this;
  }

   /**
   * Get isAdmin
   * @return isAdmin
  **/
  @Schema(required = true, description = "")
  public Boolean isIsAdmin() {
    return isAdmin;
  }


  @Override
  public String toString() {
    return "{"
        + "canAccess: " + toIndentedString(canAccess) + ","
        + " canViewPII: " + toIndentedString(canViewPII) + ","
        + " canSendFolio: " + toIndentedString(canSendFolio) + ","
        + " canSendGRU: " + toIndentedString(canSendGRU) + ","
        + " isAdmin: " + toIndentedString(isAdmin)
        + "}";
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
